name: CI

on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-latest

    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/LCM-MTK/android_kernel_mediatek_mt6757
          kernel-branch: lineage-15.1
          config: k57pv1_dm_64_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: false
          android-version: 12
          aosp-clang-version: r383902
          anykernel3: true
